In [2]:
import numpy as np
a=np.array
print(a)

<built-in function array>


In [13]:
#Array creation and variables
a1 = np.array([1, 2, 3])  
print(a1)
arr2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]])  
print(arr2)
print(arr2.ndim)
print(arr2.itemsize)
print(arr2.dtype)
print(arr2.size)
print(arr2.shape)

[1 2 3]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 23]]
2
4
int32
12
(3, 4)


In [18]:
#Array Functions
a1=np.array([[1,2],[3,4],[5,6]])  
print(a1.shape)
a2=a1.reshape(2,3)
print(a2)
print(a2.shape)
print(a1.max())
print(a1.min())
print(a1.sum())

(3, 2)
[[1 2 3]
 [4 5 6]]
(2, 3)
6
1
21


In [53]:
print(a1.max(axis=1))
print(a1.max(axis=0))
print(a1.sum(axis=0))
print(a1.sum(axis=1))

[2 4 6]
[5 6]
[ 9 12]
[ 3  7 11]


In [ ]:
#Array Slicing
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr1[:4])
print(arr1[2:])
print(arr1[-3:-1])
print(arr1[1:5:2])
print(arr1[::2])
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[1,1:4])
print(arr2[0:2,1])#From both the elements return index 1
print(arr2[0:2,1:3])

In [26]:
#Arithmetic Opearations in array
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 2  4 33]
 [22 34 33]]
[[  0   0  27]
 [ -2  -4 -25]]
[[  1   4  90]
 [120 285 116]]
[[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [51]:
#Array Cocatenation and splitting
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print(np.concatenate((a,b)))
print("_____________")
print(np.vstack((a,b)))
print("_____________")
print(np.hstack((a,b)))
print("_____________")
print(np.array_split(a,2))
print("_____________")
print(np.hsplit(b,3))
print("_____________")

[[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
_____________
[[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
_____________
[[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]
_____________
[array([[ 1,  2, 30]]), array([[10, 15,  4]])]
_____________
[array([[ 1],
       [12]]), array([[ 2],
       [19]]), array([[ 3],
       [29]])]
_____________


In [1]:
#Array Creation
arr = np.empty((3,2), dtype = int) 
print(arr)
arr0=np.zeros((3,3),dtype=int)
print(arr0)

NameError: name 'np' is not defined

In [ ]:
#Datatype conversion
arr = np.array([1.1, 2.1, 3.1])

newarr = arr1.astype('i')
newarr1 = arr1.astype(int)
print(newarr)
print(newarr.dtype)

In [32]:
#Converting collections to array
l=[1,2,3,4,5,6,7]  
a = np.asarray(l);  
print(type(a))  
print(a)  
t=(1,2,3,4)
b=np.asarray(t)
print(b)
print(type(b))

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]
[1 2 3 4]
<class 'numpy.ndarray'>


In [34]:
#Arrays in a range
arr = np.arange(0,10,2,float)  
print(arr)  
arr1 = np.arange(10,100,5,int) 
print(arr1)

[0. 2. 4. 6. 8.]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [60]:
#Array iteration
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
print("Printing array:")  
print(a);  
print("Iterating over the array:")  
for x in np.nditer(a):  
    print(x,end=' ')
print(end=' ')
print("-------------------")
at=a.T
print(at)

Printing array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3  -------------------
[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]


In [71]:
#Iterating in arrays
arr = np.array([1, 2, 3])
for x in arr:
    print(x)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
for y in arr1:
    print(y)
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr2[1,1])

1
2
3
[1 2 3]
[4 5 6]
[10 11 12]


In [55]:
#Copy VS View
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 42

print(arr)
print(x)
y = arr.view()
arr[0] = 42

print(arr)
print(y)
print(x.base)
print(y.base)

[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[42  2  3  4  5]


In [59]:
#Sorting and Searching
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
  
print("Sorting along the columns:")  
print(np.sort(a))  
  
print("Sorting along the rows:")  
print(np.sort(a, 0))  
  
print(np.sort(a, 0,'heapsort')) 

arr = np.array([1, 2, 3, 4, 15, 4, 7, 4])
x=np.where(arr==4)
print(x)
y=np.where(arr%2==1)
print(y)

Sorting along the columns:
[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]
Sorting along the rows:
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
(array([3, 5, 7], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


In [72]:
#Array Filtering
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)
filter_arr=arr%2==0
newarr1=arr[filter_arr]
print(newarr1)

[41 43]
[42 44]
