numpy

In [3]:
import numpy as np
a=np.array
print(a)

<built-in function array>


In [56]:
a1=np.array([1,2,3])
#print(a1)
arr = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [1, 2, 3], [4, 5, 6] ] ])
arr2=np.array([[1,2,3,4],[4,5,6,7],[9,10,11,23]])
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
#print(arr2)
#print(arr.ndim)
#print(arr2.itemsize)
print(a1(

TypeError: 'numpy.ndarray' object is not callable

In [17]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [21]:
#returns number oof elements in an array
print(arr1.itemsize,arr2.itemsize,arr3.itemsize)

4 4 4


In [24]:
#datatype of array
print(arr.dtype,arr2.dtype,arr3.dtype)

int32 int32 int32


In [30]:
#numbers of ellement in an array
print(arr1.size,arr2.size)

5 6


In [33]:
print(arr3.shape)

(2, 2, 3)


In [43]:
#array function 
a1=np.array([[1,2],[3,4],[5,6]]) 
a1.shape
a2=a1.reshape(2,3)
a2.shape
a2
a2.max()
a1.min()
a1.sum()

21

In [51]:
print(a1,"sep",a2)

[[1 2]
 [3 4]
 [5 6]] sep [[1 2 3]
 [4 5 6]]


In [53]:
print(a1.(axis=1))

SyntaxError: invalid syntax (2419781871.py, line 1)

In [64]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3.min(axis=1))
print(arr3.max(axis=1))
print(arr3.sum(axis=1))
print(arr3.squareroot(axis=1))


[1 4]
[3 6]
[ 6 15]


AttributeError: 'numpy.ndarray' object has no attribute 'squareroot'

In [70]:
b=np.array([[1,2],[3,4],[5,6]])
print(b.shape)
b.reshape(1,6)

(3, 2)


array([[1, 2, 3, 4, 5, 6]])

In [100]:
# #Array Slicing
arr2=np.array([1,2,3,4,5,6,7])
#print(arr2[1:4])
print(arr2[0:7:1])
print(arr2[2:])
print(arr1[1:5:2])
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[1,1:4])
# print(arr2[0:2,1])
# print(arr2[0:2,1:3])

[1 2 3 4 5 6 7]
[3 4 5 6 7]
[2 4]
[7 8 9]


In [88]:
l=[1,2,3,4,5,6]
z=(l[0:6:-1])
print(z)

[]


In [87]:
l="abhisheikh"
z=(l[::-1])

hkiehsihba


In [134]:
arr=np.array([1,2,3,4])
arr2=np.array([[1,2,3],[3,4,5]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# print(arr.ndim)
# print(arr2.ndim)
# print(arr3.ndim)
# print(arr3)
#print(arr3)
print(arr2.shape)
c=arr2.reshape(3,2)
print(c.shape)
print(arr2)
print(c)
print(arr3.reshape(12,))
print(arr3.max())
print(arr3.min())
print(arr3.sum())

(2, 3)
(3, 2)
[[1 2 3]
 [3 4 5]]
[[1 2]
 [3 3]
 [4 5]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
12
1
78


In [139]:
#axis
#0=column
#1=row
arr=np.array([1,2,3,4])
arr2=np.array([[1,2,3],[3,4,5]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr2)
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))

[[1 2 3]
 [3 4 5]]
[4 6 8]
[ 6 12]


In [140]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c=arr3.reshape(12,)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [151]:
print(c[:4])
print(c[2:10:2])
print(arr3[0:1][0:1])
print(c[-12:-1:-1])

[1 2 3 4]
[3 5 7 9]
[[[1 2 3]
  [4 5 6]]]
[]


In [156]:
a=np.array([1,2,3])
b=np.array([[4,5,6],[1,2,3]])
c=np.array([[[1],[2]],[[3],[4]]])
#print(a[::-1])

print(c[::-])

[[[3]
  [4]]]


In [169]:
#arithmatic operation 
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)

[ 6  8 10 12]


In [170]:
a=[1,2,3],[4,5,6],[9,8,7],[6,5,4]
b=[9,8,7],[6,5,4],[1,2,3],[4,5,6]
result = [[0,0,0],[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        result[i][j] = a[i][j] + b[i][j]
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [179]:
#Array Cocatenation and splitting
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print("this is concat")
print(np.concatenate((a,b)))
print("this is vstack")
print(np.vstack((a,b)))
print("this is hstack")
print(np.hstack((a,b)))


this is concat
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
this is vstack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
this is hstack
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [183]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print("this is array split")
print(np.array_split(a,1))
print("this is array split")
print(np.array_split(a,2))
print("this is array split")
print(np.array_split(a,3))
print("this is array split")
print(np.array_split(a,4))
print("this is array split")
print(np.array_split(a,5))

this is array split
[array([[1, 2, 3],
       [4, 5, 6]])]
this is array split
[array([[1, 2, 3]]), array([[4, 5, 6]])]
this is array split
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]
this is array split
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32)]
this is array split
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32)]


In [186]:
#horizontle split

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.hsplit(b,3)
print(c)

[array([[ 7],
       [10]]), array([[ 8],
       [11]]), array([[ 9],
       [12]])]


In [210]:
#array creation 
abc=np.empty((3,2),dtype =int)
print("abc",abc)
abcd=np.zeros((3,3),dtype=int)
print("abcd",abcd)
abcde=np.ones((3,3,1),dtype=int)
print("abcde",abcde)

abc [[0 0]
 [1 0]
 [1 0]]
abcd [[0 0 0]
 [0 0 0]
 [0 0 0]]
abcde [[[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]]


In [217]:
#datatype Conversion
dhiraj=np.array([1.1,2.1,3.1])
newarr=dhiraj.astype('i')
#newarr=dhiraj.astype('f')
print(newarr)
newarr1=dhiraj.astype(int)
newarr1=dhiraj.astype(float)
print(newarr1)

[1 2 3]
[1.1 2.1 3.1]


In [220]:
#converting collection to an array

#list

l=[1,2,3,4,5,6,7,8,9]
print(type(l))
a=np.asarray(l)
print(a)
print(type(a))

<class 'list'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [227]:
#tuple
a=(1,2,3,4)
print(type(a))
abhisheikh=np.array(a)
abhisheikh=np.asarray(a)
print(abhisheikh)
print(type(abhisheikh))

<class 'tuple'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [235]:
arr = np.array([[[1, 2, 3], [4, 5, 87]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0,1,2])
print(arr[0:1:2])

87
[[[ 1  2  3]
  [ 4  5 87]]]


In [238]:
#array iteration
abc=np.array([1,2,3,4])
print(abc)
for i in abc:
    print(i)
    print("iterated")

[1 2 3 4]
1
iterated
2
iterated
3
iterated
4
iterated


In [243]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]]) 
#nditer number of dimentions iterated 
for x in np.nditer(a):
    print(x,end=" ")

1 2 3 4 2 4 5 6 10 20 39 3 [[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]


In [245]:
#T stands for transpose
rt=a.T
print(rt)

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]


In [257]:
#Copy VS View
arr = np.array([1,2,3,4,5])
x=arr.copy()
x[0]=42

#print(arr)
#print(x)
y=arr.view()
arr[0]=42

print("this is default array",arr)
print("this is view",y)
print("this is base of x",x.base)
print("this is base of y",y.base)

this is default array [42  2  3  4  5]
this is view [42  2  3  4  5]
this is base of x None
this is base of y [42  2  3  4  5]


In [16]:
#sorting & searching
import numpy as np
a = np.array([[10,2,3],[4,5,6],[7,58,9]])
print(a)
print("sorting along columns")
print(np.sort(a))
print("Sorting along the rows:")  
print(np.sort(a,0))  

[[10  2  3]
 [ 4  5  6]
 [ 7 58  9]]
sorting along columns
[[ 2  3 10]
 [ 4  5  6]
 [ 7  9 58]]
Sorting along the rows:
[[ 4  2  3]
 [ 7  5  6]
 [10 58  9]]


In [20]:
#Array Filtering
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr=arr[x]
print (newarr)
filter_arr=arr%2==0
newarr1=arr[filter_arr]
print(newarr1)

[41 43]
[42 44]


pandas

In [3]:
import pandas as pd
infi_nums=pd.DataFrame({})

#remove duplicates
emp = {"name":["Rajesh","sunita","mamata","rajesh"],
      "Age":[21,32,29,21]
      }
info()

NameError: name 'info' is not defined

In [2]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string()) 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [5]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [6]:
print(pd.__version__)

1.5.1


In [35]:
import pandas as pd
a=[1,2,3,4]
x=pd.Series(a)
#b=pd.Series(([1,2,3],index("a","b","c")))
print(x)

0    1
1    2
2    3
3    4
dtype: int64


In [27]:
a=[1,2,3]
b=pd.Series(a,index=["a","b","c"])
print(b)

a    1
b    2
c    3
dtype: int64


In [30]:
x=pd.Series([1,2,3],index = ['a','b','c'])
print(x)

a    1
b    2
c    3
dtype: int64


In [31]:
print(x["a"])

1


In [33]:
friends={"abishek":1,"dhiraj":2,"rohit":3}
dbda=pd.Series(friends)
#print(dbda)
dbda

abishek    1
dhiraj     2
rohit      3
dtype: int64

In [39]:
friends={"abishek":1,"dhiraj":2,"rohit":3}
dbda=pd.Series(friends,index=["abhishek","dhiraj","rohit"])
print(dbda)

abhishek    NaN
dhiraj      2.0
rohit       3.0
dtype: float64


In [46]:
#friends={"abishek":1,"dhiraj":2,"rohit":3}
friends=["Abhi","dhiraj","rohit"]
marks=[100,200,300]
dbda=pd.DataFrame(friends,marks)
#print(dbda)
dbda

0
100    Abhi
200  dhiraj
300   rohit

In [53]:
set1={
    "friends":["Abhi","dhiraj","rohit"],
    "marks":[100,200,300]}

dbda=pd.DataFrame(set1)
dbda

friends  marks
0    Abhi    100
1  dhiraj    200
2   rohit    300

In [57]:
dbda.to_csv("set1.csv")

In [62]:
dbda.to_string()

'  friends  marks\n0    Abhi    100\n1  dhiraj    200\n2   rohit    300'

matplotlib

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [70]:
data=pd.read_csv("data.csv")
c1=pd.DataFrame(data)
print(c1)
duration_count=list(c1.groupby('Duration').Duration.agg("count"))
print(duration_count)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]
[2, 9, 1, 16, 35, 79, 2, 1, 8, 3, 4, 2, 3, 2, 1, 1]


In [77]:
def sum1(a,b):
    print("a is",a)
    print("b is",b)
    return a*b


z=sum1(1,2)
print("multiplication is",z)



a is 1
b is 2
multiplication is 2


In [78]:
import calc

ModuleNotFoundError: No module named 'calc'

In [79]:
from turtle import *
color('red', 'yellow')
begin_fill()
while True:
    forward(200)
    left(170)
    if abs(pos()) < 1:
        break
end_fill()
done()

beautifulsoup

In [8]:
from  bs4 import BeautifulSoup
soup=BeautifulSoup('<b class="boldest">Extremely bold</b>')
tag=soup.b
type(tag)

bs4.element.Tag

In [18]:
html_doc="""
<html>
<head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
</body>
</html>
"""
from bs4 import BeautifulSoup
soup=BeautifulSoup(html_doc,"html.parser")
head_tag=soup.head
head_tag

<head><title>The Dormouse's story</title></head>

In [6]:
body_tag=soup.body
body_tag

<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>
<p class="story">...</p>
</body>

In [11]:
print(head_tag.contents)

[<title>The Dormouse's story</title>]


In [12]:
print(body_tag.contents)

['\n', <p class="title"><b>The Dormouse's story</b></p>, '\n', <p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>, '\n', <p class="story">...</p>, '\n']


In [14]:
a=head_tag.strings
print(a)

<generator object Tag._all_strings at 0x0000026F009A43C0>


In [15]:
tag_title=soup.title
tag_title

In [20]:
print(soup.title)

<title>The Dormouse's story</title>


In [21]:
soup.head

<head><title>The Dormouse's story</title></head>

In [24]:
soup.p

<p class="title"><b>The Dormouse's story</b></p>

In [30]:
tag_body=soup.body
print(tag_body.contents)

['\n', <p class="title"><b>The Dormouse's story</b></p>, '\n', <p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>, '\n', <p class="story">...</p>, '\n']


In [31]:
bodytags = soup.body
for child in bodytags.children:
    print(child)



<p class="title"><b>The Dormouse's story</b></p>


<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>


<p class="story">...</p>




In [34]:
bodytags = soup.body
for parent in bodytags.descendants:
    print(parent)



<p class="title"><b>The Dormouse's story</b></p>
<b>The Dormouse's story</b>
The Dormouse's story


<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>
Once upon a time there were three little sisters; and their names were

<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>
Elsie
,

<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>
Lacie
 and

<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>
Tillie
;
and they lived at the bottom of a well.


<p class="story">...</p>
...


