In [4]:
import numpy as np
#import numpy
a=np.array
print(a)


<built-in function array>


In [18]:
#Array creation and variables
a1 = np.array([1, 2, 3])  
#print(a1)
a2=np.array([[1,2],[3,4]])
#print(a2)
arr2 = np.array([[1, 2, 3, 4,5], [4, 5, 6, 7,6], [9, 10, 11, 23,8]])  
print(arr2)
print(a2.ndim)
print(arr2.itemsize)
print(arr2.dtype)
print(arr2.size)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 4  5  6  7  6]
 [ 9 10 11 23  8]]
2
4
int32
15
(3, 5)


In [31]:
#Array Functions
a1=np.array([[1,2],[3,4],[5,6],[8,9]])
print(a1)
#a1=a3
print(a1.shape)
a1=a1.reshape(2,4)
#print(a2)
#print(a2.shape)
print(a1)
print(a1.max(axis=1))
print(a1.min(axis=0))
print(a1.sum(axis=0))

[[1 2]
 [3 4]
 [5 6]
 [8 9]]
(4, 2)
[[1 2 3 4]
 [5 6 8 9]]
[4 9]
[1 2 3 4]
[ 6  8 11 13]


In [53]:
print(a1.max(axis=1))
print(a1.max(axis=0))
print(a1.sum(axis=0))
print(a1.sum(axis=1))

[2 4 6]
[5 6]
[ 9 12]
[ 3  7 11]


In [38]:
#Array Slicing
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr1[0:7])
print(arr1[2:])
print(arr1[-3:-1])
print(arr1[0:5:2])
#print(arr1[::2])
#arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#print(arr2[1,1:4])
#print(arr2[0:2,1])#From both the elements return index 1
#print(arr2[0:2,1:3])

[1 2 3 4 5 6 7]
[3 4 5 6 7]
[5 6]
[1 3 5]


In [43]:
#Arithmetic Opearations in array
a = np.array([[1,2,3],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 2  4  6]
 [22 34 33]]
[[  0   0   0]
 [ -2  -4 -25]]
[[  1   4   9]
 [120 285 116]]
[[1.         1.         1.        ]
 [0.83333333 0.78947368 0.13793103]]


In [55]:
#Array Cocatenation and splitting
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
#print(np.concatenate((a,b)))
#print("_____________")
#print(np.vstack((a,b)))
#print("_____________")
#print(np.hstack((a,b)))
#print("_____________")
#print(np.array_split(a,2))
#print("_____________")
a1=np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])
print(np.array_split(a1,2))
#print(np.hsplit(b,3))
#print(np.hsplit(a1,3))
print("_____________")

[array([[1, 2, 3, 4, 5, 6]]), array([[11, 12, 13, 14, 15, 16]])]
_____________


In [61]:
#Array Creation
arr = np.ones((3,2), dtype = int,order='C') 
print(arr)
#arr0=np.zeros((3,3),dtype=int)
#print(arr0)

[[1 1]
 [1 1]
 [1 1]]


In [65]:
#Datatype conversion
arr = np.array([1.1, 2.1, 3.1])
#print(arr.dtype)
#arr1=np.array([1,2,3])
newarr = arr.astype('i')
#newarr1 = arr1.astype(int)
print(newarr)
#print(newarr.dtype)

[1 2 3]


In [70]:
#Converting collections to array
l=[1,2,3,4,5,6,7]  
print(type(l))
#print(l)
a = np.asarray(l); 
#print(a)
#print(type(a))  
#print(a)  
t=(1,2,3,4)
b=np.asarray(t)
print(b)
#print(type(b))

<class 'list'>
[1 2 3 4]


In [74]:
#Arrays in a range
#arr = np.arange(0,10,2,float)  
arr = np.arange(0,10,1,float) 
print(arr)  
#arr1 = np.arange(10,100,5,int) 
#print(arr1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [79]:
#Array iteration
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
#print("Printing array:")  
print(a)
#print("Iterating over the array:")  
#for x in np.nditer(a):  
    #print(x,end=' ')
#print(end=' ')
#print("-------------------")
at=a.T
print(at)

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]


In [71]:
#Iterating in arrays
arr = np.array([1, 2, 3])
for x in arr:
    print(x)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
for y in arr1:
    print(y)
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr2[1,1])

1
2
3
[1 2 3]
[4 5 6]
[10 11 12]


In [82]:
#Copy VS View
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
#x[0] = 42

#print(arr)
#print(x)
#y = arr.view()
y[0] = 43

print(arr)
print(y)
#print(x.base)
#print(y.base)

[43  2  3  4  5]
[43  2  3  4  5]


In [91]:
#Sorting and Searching
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
print(a) 
#print("Sorting along the columns:")  
#print(np.sort(a,0))  
  
#print("Sorting along the rows:")  
#print(np.sort(a, 0))  
  
#print(np.sort(a)) 
#print(np.sort(a))
arr = np.array([1, 2, 3, 4, 15, 4, 7, 4])
x=np.where(arr==2)
print(x)
#y=np.where(arr%2==1)
#print(y)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
(array([1], dtype=int64),)


In [94]:
#Array Filtering
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

#print(newarr)
filter_arr=arr%2==0
print(filter_arr)
newarr1=arr[filter_arr]
print(newarr1)

[False  True False  True]
[42 44]
