In [6]:
#Series and Dataframe
import pandas as pd
data1=[0,1,2,3,4,5]
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}
myseries=pd.Series(data1)
myvar = pd.DataFrame(mydataset)
mydata1=pd.DataFrame(data1)
print(myseries)
print("-"*100)
print(myvar)
print("-"*100)
print(mydata1)
print("-"*100)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
----------------------------------------------------------------------------------------------------
    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
----------------------------------------------------------------------------------------------------
   0
0  0
1  1
2  2
3  3
4  4
5  5
----------------------------------------------------------------------------------------------------


In [20]:
#Series in Pandas and object attributes
import pandas as pd  
import numpy as np  
#Create series using array
info = np.array(['P','a','n','d','a','s'])  
a = pd.Series(info)  
print(a) 
#Create series usng dictionary
info1 = {'x' : 0., 'y' : 1., 'z' : 2.}  
a1 = pd.Series(info1)  
print (a1)
# Create series using scalar
x = pd.Series(4, index=[0, 1, 2, 3])  
print (x)  
#Create series using indexes
x1 = pd.Series([1,2,3],index = ['a','b','c'])  
#retrieve the first element  
print (x1) 
print(x1.index)
print(x1.shape)
print(x1.dtype)
print(x1.size)
print(x1.empty)
print(x1.hasnans)
print(x1.nbytes)
print(x1.ndim)
#print(x1.itemsize)

0    P
1    a
2    n
3    d
4    a
5    s
dtype: object
x    0.0
y    1.0
z    2.0
dtype: float64
0    4
1    4
2    4
3    4
dtype: int64
a    1
b    2
c    3
dtype: int64
Index(['a', 'b', 'c'], dtype='object')
(3,)
int64
3
False
False
24
1


In [34]:
#Series Functions

x = pd.Series([1,2,3,np.NAN],index = ['a','b','c','d'])  
print(x)
print(len(x))
print(x.count())
a=pd.Series([1,2,3,4,5,3,4,5])
b=pd.Series([6,7,8,9,10])
print(a.std())
print(a.max())
print(a.unique())
print(a.value_counts())

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64
4
3
1.407885953173359
5
[1 2 3 4 5]
3    2
4    2
5    2
1    1
2    1
dtype: int64


In [9]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [45]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45],
    "one":[1,2,3],
    "two":[1,2,3]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 
#info = {'one' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f']),  
 #  'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])}  
  
#d1 = pd.DataFrame(info)  
#Column Selection
print (df['one'])   
#Column Addition
df['three']=df['one']+df['two']
print(df)
#Column Deletion:
#del df['one']
#Row Selection
print(df.iloc[0])
print(df[2:3])


   calories  duration  one  two
0       420        50    1    1
1       380        40    2    2
2       390        45    3    3
0    1
1    2
2    3
Name: one, dtype: int64
   calories  duration  one  two  three
0       420        50    1    1      2
1       380        40    2    2      4
2       390        45    3    3      6
calories    420
duration     50
one           1
two           1
three         2
Name: 0, dtype: int64
   calories  duration  one  two  three
2       390        45    3    3      6


In [52]:
#DataFrame Aggregate Functions
info1 = pd.DataFrame({"x":[25,15,12,19],   
                    "y":[47, 24, 17, 29]})     
# Create second Dataframe using dictionary   
info2 = pd.DataFrame({"x":[25, 15, 12],   
                    "y":[47, 24, 17],    
                    "z":[38, 12, 45]})   
# append info2 at end in info1   
print(info1.agg(['sum','min','max']) ) 
print(info1)

      x    y
sum  71  117
min  12   17
max  25   47
    x   y
0  25  47
1  15  24
2  12  17
3  19  29


In [62]:
#Assign function
# Create an empty dataframe  
info = pd.DataFrame()  
  
# Create a column  
info['ID'] = [101, 102, 103]
print(info)
info1=info.assign(Name = ['Smith', 'Parker', 'John'])  
print(info1)
info1=info1.assign(Mark1=[79,67,89])
info1=info1.assign(Mark2=[79,67,89])
info1=info1.assign(Total=lambda x: x.Mark1+x.Mark2)
print(info1)
print(info1.count())

    ID
0  101
1  102
2  103
    ID    Name
0  101   Smith
1  102  Parker
2  103    John
    ID    Name  Mark1  Mark2  Total
0  101   Smith     79     79    158
1  102  Parker     67     67    134
2  103    John     89     89    178
ID       3
Name     3
Mark1    3
Mark2    3
Total    3
dtype: int64


In [72]:
info_nums = pd.DataFrame({'num': np.arange(0,100,5,int) })  
print(info_nums)  
info_nums['num_bins'] = pd.cut(x=info_nums['num'], bins=[1,25])  
print(info_nums)  
info1_nums=info_nums
print(info_nums['num_bins'].unique())  
print(info_nums.describe())


    num
0     0
1     5
2    10
3    15
4    20
5    25
6    30
7    35
8    40
9    45
10   50
11   55
12   60
13   65
14   70
15   75
16   80
17   85
18   90
19   95
    num     num_bins
0     0          NaN
1     5  (1.0, 25.0]
2    10  (1.0, 25.0]
3    15  (1.0, 25.0]
4    20  (1.0, 25.0]
5    25  (1.0, 25.0]
6    30          NaN
7    35          NaN
8    40          NaN
9    45          NaN
10   50          NaN
11   55          NaN
12   60          NaN
13   65          NaN
14   70          NaN
15   75          NaN
16   80          NaN
17   85          NaN
18   90          NaN
19   95          NaN
[NaN, (1.0, 25.0]]
Categories (1, interval[int64, right]): [(1, 25]]
             num
count  20.000000
mean   47.500000
std    29.580399
min     0.000000
25%    23.750000
50%    47.500000
75%    71.250000
max    95.000000


In [74]:
#Removing duplicates
emp = {"Name": ["Parker", "Smith", "William", "Parker"],  
"Age": [21, 32, 29, 21]}  
info = pd.DataFrame(emp)  
info = info.drop_duplicates()  
print(info)  

      Name  Age
0   Parker   21
1    Smith   32
2  William   29


In [90]:
#Head function
d1=pd.DataFrame({'num1': np.arange(0,100,5,int) }) 
d2=pd.DataFrame({'num2': np.arange(0,100,5,int) }) 
print(d1.head())
print(d1.mean())


   num1
0     0
1     5
2    10
3    15
4    20
num1    47.5
dtype: float64


In [97]:
#merge and rename function
left = pd.DataFrame({  
   'id':[1,2,3,4,5],  
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],  
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})  
right = pd.DataFrame({  
    'id':[1,2,3,4,5],  
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],  
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})  
d3=pd.merge(left,right,on='id')  
print(d3)
d3.rename(columns = {'Name_x':'Name'}, inplace = True)
print(d3)

   id  Name_x subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5
   id    Name subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5


In [98]:
#sample function
d1=pd.DataFrame({'num1': np.arange(0,100,5,int) }) 
d2=d1.sample(n=3)
print(d2)

   num1
0     0
5    25
1     5


In [103]:
#shift function
d1=pd.DataFrame({'num1': np.arange(0,100,5,int) }) 
d2=d1.shift(periods=2,axis=1,fill_value=70)
#d2=d1.shift(periods=2)
print(d2)

    num1
0     70
1     70
2     70
3     70
4     70
5     70
6     70
7     70
8     70
9     70
10    70
11    70
12    70
13    70
14    70
15    70
16    70
17    70
18    70
19    70


In [116]:
#Sort function
info = pd.DataFrame(index=[3,4,1,2])
info = pd.DataFrame({'col1':[7,1,8,3],'col2':[8,12,4,9]})  
print(info) 
info1=info.sort_values(by='col1')
print(info1)
#transpose function
print(info1.transpose())
#Adding columns
info1['colum3']=24
print(info1)
#converting to numpy array
a=info1.to_numpy()
print(a)

   col1  col2
0     7     8
1     1    12
2     8     4
3     3     9
   col1  col2
1     1    12
3     3     9
0     7     8
2     8     4
       1  3  0  2
col1   1  3  7  8
col2  12  9  8  4
   col1  col2  colum3
1     1    12      24
3     3     9      24
0     7     8      24
2     8     4      24
[[ 1 12 24]
 [ 3  9 24]
 [ 7  8 24]
 [ 8  4 24]]


In [25]:
df = pd.read_csv('data.csv')

#print(df) 
print(pd.options.display.max_rows) 
pd.options.display.max_rows = 9999

#print(df.head())
#print(df.tail())
#print(df.info())
#df = pd.read_csv('data.csv')

new_df = df.dropna()

print(new_df.to_string())
new_df.to_csv('data1.csv')

9999
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         